name: Docs

on: { workflow_call: {} }

jobs:
  docs:
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      matrix:
        crate:
          - solti-api
          - solti-core
          - solti-exec
          - solti-model
          - solti-observe
          - solti-prometheus
    steps:
      - uses: actions/checkout@v4
      - name: Run docs gen
        uses: soltiHQ/actions/taskfile@main
        with:
          command: cargo/docs CRATE=${{ matrix.crate }}